version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    open-pull-requests-limit: 20
    groups:
      all-gradle-dependencies:
        patterns:
          - "*"  # Matches every dependency in this ecosystem