name: Deploy to Play Store
on:
  push:
    branches:
      - master

jobs:
  package-signed-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > release.keystore
          ls -alh
          pwd

      - name: Set Package Version with RunID
        run: |
          NEW_ID=$((${{ github.run_number }} + 200))
          echo "The new ID is $NEW_ID"

          sed -i "s/115/$NEW_ID/g" app/build.gradle
          sed -i "s/1.15/$NEW_ID/g" app/build.gradle
          cat app/build.gradle

      - name: Build & Sign AAB
        run: gradle bundleRelease # Ensure your build.gradle handles signing via env vars
        env:
          KEYSTORE_PATH: /home/runner/work/jpi-edm-utility/jpi-edm-utility/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}


      - run: ls -alh app/build/outputs/bundle/release/
      - uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/app-release.aab


  publish-for-internal-testing:
    runs-on: ubuntu-latest
    needs: package-signed-aab
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: signed-aab

    - uses: r0adkll/upload-google-play@935ef9c68bb393a8e6116b1575626a7f5be3a7fb
      with:
        serviceAccountJsonPlainText: ${{ secrets.GHA_SERVICE_USER_JSON }}
        packageName: com.zerotreedelta.jpi.upload
        releaseFiles: app-release.aab
        track: qa
        status: inProgress
        #whatsNewDirectory: distribution/whatsnew
        #mappingFile: app/build/outputs/mapping/release/mapping.txt
        #debugSymbols: app/intermediates/merged_native_libs/release/out/lib